#!/usr/bin/bash

yum install tomcat -y --skip-broken
sed -i 's/port="8080"/port="8880"/' /etc/tomcat/server.xml
yum install tomcat-webapps tomcat-admin-webapps -y --skip-broken
yum install tomcat-docs-webapp tomcat-javadoc -y --skip-broken
